version: '3.7'
services:
  mongo:
    hostname: mongodb
    container_name: mongodb-docker
    image: mongo:latest
    expose:
      - 27017
    ports:
      - 27017:27017
    restart: always
  backend:
    build: backend
    ports:
      - 8080:8080
    links:
      - mongo
  frontend:
    build: frontend
    ports:
      - 3000:3000